<?php

declare(strict_types=1);

namespace src\Modules\Report\Domain\Enum;

enum CodeExceptionEnum: int
{
    case INVALID_REPORT_ID = 2001;

    case INVALID_REPORT_REVISION = 2002;

    case REPORT_ALREADY_GENERATED = 2003;

    case REPORT_NOT_GENERATED = 2004;

    case INCOMPLETE_REPORT = 2005;

    case INVALID_MUNICIPALITY = 2006;

    case INVALID_REPORT_TYPOLOGY = 2007;

    case INVALID_SEI_NUMBER = 2008;

    case FUTURE_INSPECTION_DATE = 2009;

    case INVALID_REPORT_COLLABORATORS = 2010;

    case INVALID_REPORT_FILE_REFERENCE = 2011;

    case REPORT_IMAGE_TOO_LARGE = 2012;

    case INVALID_REPORT_IMAGE_FORMAT = 2013;

    case DUPLICATE_REPORT_FILE = 2014;

    case TOO_MANY_REPORT_FIGURES = 2015;

    case INVALID_REPORT_IMAGE_ORDER = 2016;

    case REPORT_ATTACHMENT_DESCRIPTION_REQUIRED = 2017;

    case INVALID_REPORT_CONCLUSION = 2018;

    case INVALID_REPORT_STATUS = 2019;

    case INVALID_REPORT_DATE = 2020;

    case INVALID_REPORT_IMAGE_CAPTION = 2021;

    case INVALID_GENERATED_REPORT = 2022;

    case INVALID_REPORT_ATTACHMENT = 2023;

}
